### ISSUE TITLE
Api: allow using `lambda.Function` for routes

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#1078]
Currently only `sst.Function` can be used with other SST constructs. We should allow `lambda.Function` to be used. This allows ppl to use runtimes not supported by `sst.Function`.

Test `sst.Function.fromFunctionArn` can be used as routes/subscribers/consumers/resolvers. And test the function works fine in Console.

---
Requests:
- George Evans & Guy Shechter https://serverless-stack.slack.com/archives/C01JG3B20RY/p1637756792249100
- Adrian Mouly https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1637901893354900
- Brinsley https://serverless-stack.slack.com/archives/C01JG3B20RY/p1650968470930639

**Comment by danieloi** [comment]
Here're some of my findings investigating this issue

- builds work fine when I just return the `definition` [here](https://github.com/serverless-stack/serverless-stack/blob/6499706b09f33bf4327bf3fdf54423a60813c3aa/packages/resources/src/Function.ts#L528) instead of throwing an error
- successfully deployed lambda.Function instances return `internal server error` when I use ES6 module syntax like ‘export’ instead of commonjs syntax like ‘exports.handler’. They return 200s otherwise.
- the new console at console.serverless-stack.com breaks when I use lambda.Function instead of sst.Function

I'm figuring out the commonjs issue and tackling the console issues afterwards.

I sense notifying everyone of unwatched files in the cli and web console would be a part of a solution to this once these other issues are ironed out.

Any pointers or things I haven't considered? Please share. I'll be hacking away based on these points for now.

**Comment by fwang** [comment]
Thanks for looking into this @danieloi.

With the approach you suggested, wouldn't there be a type error? `Function.fromDefinition` is expected to return type `sst.Function`, but if we returned the `definition` as suggested above, the function returns type `lambda.Function`?

How about let's take another approach. Instead of making `sst.Function` take `lambda.Function`, we make other constructs to take both `sst.Function` and `lambda.Function`. We don't have to do this for all constructs, let's just do it for the `Api` constructs as both requests in this issue were looking to use `lambda.Function` as `Api` routes.

**Comment by fwang** [comment]
You can now use `lambda.Function` for routes in v1.6.10. Here's an example https://docs.sst.dev/constructs/Api#creating-lambda-container-images
