### ISSUE TITLE
Fargate support

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#2106]
Quite a few teams are using ECS Fargate in SST using CDK constructs, and are interested in native SST support.

### Use cases
Is it fair to classify Fargate use cases into: "services" and "tasks".
- A. "services" are long lived, and usually used with ALBs. ie, running web servers;
- B. "tasks" are short lived, they perform a task and then ends.

### What can SST simplify
- Configuring networking: in use case A, configuring VPC and ALB to expose a port to the internet.
- Configuring event triggers: in use case B, configuring the Fargate task invoked by an SNS Topic, SQS Queue

### Interesting ideas
- In use case A, optionally fallback to Lambda when Fargate is under load and cannot scale up fast enough

---
Please share your use case + how SST help you.

^ Join the discussion on Discord — https://discordapp.com/channels/983865673656705025/1024752575549022288

**Comment by dangreaves** [comment]
I think the following things would be valuable for integration.

My use case is that I use Fargate to run a Next.js 13 app. I think this will become the primary way that users run Next.js on AWS, since the current [NextjsSite](https://docs.sst.dev/constructs/NextjsSite) construct lacks even full Next.js 12 support, due to it's dependency on `@sls-next/lambda-at-edge`. With Next.js 13 leaning further towards SSR, I think a truly "serverless" approach will fail to support all the new features, leading to Fargate becoming a more popular approach.

# Resource binding

The most useful thing for me would be having [Resource Binding](https://docs.sst.dev/resource-binding) available.

I should be able to do `container.bind([bucket])` to allow an ECS container access to my bucket. Then, I can access the name of the bucket using the `@serverless-stack/node/bucket` module.

ECS containers do support [environment variables](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecs-readme.html#environment-variables), so I imagine it would work similarly to Lambda does now.

# esbuild integration

The [Function](https://docs.sst.dev/constructs/Function) construct (and all the other constructs which extend it), wraps esbuild to bundle the source files. The user simply points at their handler files, and they're good to go.

At the moment with ECS, users need to write a Dockerfile. They need to run their build script prior to running CDK, or run build scripts inside the Dockerfile as part of building the image.

It would be great to have this a little more magic. Like SST knows that you're trying to run a node app, so you just point at the entrypoint source file, and good to go, without writing up a Dockerfile.

**Comment by jayair** [comment]
@dangreaves this is great. It's completely along the lines of what we've been thinking about recently.

**Comment by fwang** [comment]
Hey @dangreaves, I'm beginning to explore Fargate. Yeah we should definitely support resource binding.

I'd love to take a glimpse at ur current setup, and have a few questions around the ideal `sst dev` experience u imagine. Would love to jump on quick zoom if u r up for it.

^ lemme throw my calendar here https://calendly.com/frank-w/30min; I'm also good if other times work better (think u r 14hr ahead of me :)

**Comment by fwang** [comment]
Shout out to everyone who liked this thread, would love to learn about ur current setup and get ur help prototyping on our first container construct.

Feel free to grab a time here — https://calendly.com/frank-w/30min, or shoot me an email at frank@sst.dev with some times that work better!

/cc @lukeshay, @mikestopcontinues, @notgiorgi, @joyfulelement, @pjvds, @MakChan, @penairdes, @NicholasFields

**Comment by fwang** [comment]
Added `Service` construct in v2.23.0. [See examples here](https://docs.sst.dev/constructs/Service)

Huge thanks to everyone here 🫡
