### ISSUE TITLE
Config Top-level await is not available in the configured target environment ("node14")

### ISSUE THREAD

**Issue by witmicko** [serverless-stack/sst#2153]
Hey all, first of all, thank you for this amazing framework. 
Ran into an issue today with `@serverless-stack/node@^1.15.16`
```
✘ [ERROR] Top-level await is not available in the configured target environment ("node14")

    node_modules/@serverless-stack/node/config/index.js:17:0:
      17 │ await storeSecretsInConfig();
         ╵ ~

```
for time beeing a workaround is to use `SST_PARAM_${MY_PARAM}` env var

**Comment by LennoxSears** [comment]
any update?

**Comment by jayair** [comment]
Config needs top level await. Are you using Node 14?

**Comment by LennoxSears** [comment]
where to config sst target environment? I search the whole project(created via sst command), found some module targetting node14 and some targetting node 16

**Comment by bros4president** [comment]
@LennoxSears apparently you should configure your function construct's `bundle = { format: 'esm' }`. Otherwise it's set to `node14` and 'cjs', according to the findings reported in #1818

If you have already set it in some global scope (app or stack level), make sure you're not overwritting it in a narrower scope (stack or function level). I was facing the same problem, even though `bundle = { format: 'esm' }` was set by default at the app level, I had naively set `bundle: true` while debugging another error related to bundle config. This made my bundle default to `node14`.

Also, just in case you're setting the bundle attribute in app or stack defaults, double-check that code is run before you instantiate a function that needs it.

**Comment by LennoxSears** [comment]
@bros4president  It works ! Thank you so much~

**Comment by v-redbill** [comment]
Thanks @bros4president ! 

Had the same issue with the new Config secret binding, bundle format 'esm' fixed it.

**Comment by fwang** [comment]
Thanks @bros4president. Glad it's working for everyone!

**Comment by renanpupin** [comment]
I am also seeing the same issue. Had to change bundle format com cjs to support apollo federation. Then I am able to make the app work locally, but when I run sst build, it breaks.
<img width="547" alt="Captura de Tela 2023-11-17 às 13 36 04" src="https://github.com/sst/sst/assets/8743530/c6138d7c-163e-444d-bf4f-abd2e676bc0d">

**Comment by jayair** [comment]
Hmm where is Node 14 coming from for you?

**Comment by renanpupin** [comment]
Not sure, I am using v16.x on my local machine.
it seems that this error comes from just when I change my build output format to ".mjs". (due to errors encountered when using graphql apollo federation)
![Captura de Tela 2023-11-20 às 12 32 59](https://github.com/sst/sst/assets/8743530/43e05ba8-ec5a-42dd-b942-5fd026be3806)

**Comment by renanpupin** [comment]
Was able to reproduce/avoid it with two different configs.

If using pure functions on my route handler, it works:
<img width="1076" alt="Captura de Tela 2023-11-22 às 20 05 54" src="https://github.com/sst/sst/assets/8743530/84ea7c90-1058-4e63-8e31-106d07fe9f68">

If using ApiHandler from 'sst/node/api', it fails:
<img width="1277" alt="Captura de Tela 2023-11-22 às 20 06 29" src="https://github.com/sst/sst/assets/8743530/60d6f5cd-d4b2-481a-bdfd-7d6a00a150ca">


One detail is that both alternative works if not using bundle format "cjs"
<img width="817" alt="Captura de Tela 2023-11-22 às 20 08 44" src="https://github.com/sst/sst/assets/8743530/5ed9a0dd-c270-4cda-bbd4-c25d5312a42e">

**Comment by jayair** [comment]
Hmm how come you are using Node 14 in the second screenshot?

**Comment by renanpupin** [comment]
Same issue if forcing node18.

<img width="1046" alt="Captura de Tela 2023-11-22 às 22 08 26" src="https://github.com/sst/sst/assets/8743530/3e4d0316-64c4-44dd-93e8-794ce14b834f">

**Comment by jayair** [comment]
Hmm that's weird. Which SST version?

**Comment by renanpupin** [comment]
> Hmm that's weird. Which SST version?

"version": "2.36.1"

**Comment by jayair** [comment]
Can you create a quick repo to reproduce this?
