### ISSUE TITLE
Dev mode ignoring specified runtime and always using node16

### ISSUE THREAD

**Issue by ArranJacques** [serverless-stack/sst#2557]
If I'm using the Node runtime and have my Lambdas configured to use the Node 18 runtime, when I deploy the stack using `sst deploy --stage local` the Lambdas are deployed and configured to use the Node 18 runtime, as expected.

If I build the stack using `sst build --stage local`, the resulting CloudFormation template contains the Lambdas, configured to use the Node 18 runtime, as expected.

However, If I run `sst dev --stage local` to deploy the development stack, the Lambdas are deployed using the Node 16 runtime.

It doesn't seem to matter how I define the runtime, whether its `app.setDefaultFunctionProps`, or defining the runtime inline in the lambda, when using the dev environment, it will ignore whatever I define and use Node 16 instead.

I am using version `2.0.37`.

**Comment by jayair** [comment]
So on dev these are run locally. Is Node 16 what you have locally?

**Comment by Brian-Azizi** [comment]
I'm getting the same issue. It ignores the run time in the default function props and just uses node16. I'm running node18 locally

**Comment by jayair** [comment]
So `sst dev` uses your local Node runtime. I'd suggest upgrading it locally. Or using something like nvm or n to manage them locally.

**Comment by jayair** [comment]
So `sst dev` uses the local Node version. You can use nvm to set it to the version you want right?

**Comment by Brian-Azizi** [comment]
I think the confusion is that, on AWS, the live lambdas show as using node 16. But actually, that doesn't matter because they just delegate back to your local node process.
So, as far as I can tell, it's all fine. It's just a bit confusing to see Node16 on AWS, but it doesn't really make a difference.

**Comment by jayair** [comment]
Hmm that's a good point. I wonder what we could do there.

**Comment by hannesj** [comment]
this is actually caused by [`Function`](https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/Function.ts#L705) construct always overwriting the passed in runtime with `CDKRuntime.NODEJS_16_X`, even if you would specify your own runtime. The default runtime is [applied before](https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/Function.ts#L628), so we should just remove the overrides.

**Comment by jayair** [comment]
@fwang take a look?

**Comment by fwang** [comment]
Yeah as @Brian-Azizi pointed out, when running `SST dev`, the deployed Lambda function is a stub function that forwards the event to your local machine. After your local machine receives the event, it runs your real code using the local Node version.

This way, we don't have to maintain a stub function in each Lambda runtime.

Hope that makes sense.

Lemme know if is causing any issues @ArranJacques @thibaultdalban @Brian-Azizi @hannesj

**Comment by villelahdenvuo** [comment]
I guess this can be closed? Although updating to Node 18 LTS would be good I guess.
