### ISSUE TITLE
2.1.12 Error when running RDS migration: "Error: Cannot rollback a transaction before creating it"

### ISSUE THREAD

**Issue by sjkcodes** [serverless-stack/sst#2611]
<img width="1134" alt="Screenshot 2023-03-06 at 5 33 06 PM" src="https://user-images.githubusercontent.com/127164296/223296258-45a9bfb4-61be-4967-ac38-ef5f3f8a0ea1.png">

SST: v2.1.12
CDK: v2.62.2

This error occurs for me when running any RDS migration via the sst console after launching with `sst dev`. I reproduced it using the rest-api-postgresql template. No other errors occurred with sst dev or sst-create.

**Comment by tlpierce** [comment]
Related thread on Discord: https://discord.com/channels/983865673656705025/985224097342582865/1082291193364365332

**Comment by NigelThorne** [comment]
Is there any work around for this?

**Comment by NigelThorne** [comment]
Interestingly.. for me. the console RDS "run sql" window still works. It's just the migrations that fail. 

Running the same migrations against a local postgres database works fine. 
It seems to be the change to using `new RDSData({})` as the connection that is causing the issue. 

Looking at the code... the error comes from calling the rollback method without calling the start transaction method. (as the error says). It could also be caused by the client not returning an ID when the transactions starts.. as there is no check that an ID was received.

Having said this... It seems odd to me that it's trying to rollback the transaction anyway. This would indicate some other error is occuring causing the transaction to get rolled back, and the rollback is also failing.

**Comment by NigelThorne** [comment]
I also noticed..
![image](https://user-images.githubusercontent.com/5942/223591429-d5fbf4bf-8d00-4a58-8321-545a819282f9.png)
From the sst console I can see two databases. Mine and a postgres one. 
Postgres is the default database name if you don't specify one; but I have checked my stack several times and I only ever reference mine... so I'm not sure where the postgres database is coming from.

**Comment by sjkcodes** [comment]
Seems to be resolved as of 2.1.14
