### ISSUE TITLE
Getting started Next.js example doesn't work after following instructions

### ISSUE THREAD

**Issue by jacktomlinson** [serverless-stack/sst#2913]
Hi there,

We have followed the basic Next.js example guide on this page: https://docs.sst.dev/start/nextjs and have deployed the site to our AWS account but it doesn't work. 

We get the following error when trying to hit the Cloudfront distribution URL....

<img width="1348" alt="image" src="https://github.com/serverless-stack/sst/assets/15871032/be917e63-2770-4d0b-8f6e-448bc5eac6bf">

Any ideas on what we are doing wrong?

These are the version numbers we are using
<img width="602" alt="image" src="https://github.com/serverless-stack/sst/assets/15871032/e7ef3c2a-4018-4cab-ab40-ad031f06e37f">

Cheers
Jack

**Comment by jacktomlinson** [comment]
This is our config file as well if that helps....

```
import { SSTConfig } from "sst";
import { Bucket, NextjsSite } from "sst/constructs";

export default {
  config(_input) {
    return {
      name: "sst-spike",
      region: "eu-west-1",
    };
  },
  stacks(app) {
    app.stack(function Site({ stack }) {
      const bucket = new Bucket(stack, "public");
      const site = new NextjsSite(stack, "site", {
        runtime: "nodejs16.x",
        bind: [bucket],
      });

      stack.addOutputs({
        SiteUrl: site.url,
      });
    });
  },
} satisfies SSTConfig;
```

**Comment by fwang** [comment]
Hey @jacktomlinson, just fixed this in [OpenNext v1.3.6](https://github.com/serverless-stack/open-next/releases/tag/v1.3.6).

If you deploy again, it should automatically pick up the new OpenNext version.

Let me know if the fix works for you.

**Comment by jacktomlinson** [comment]
Hey @fwang thanks for looking at this!

I've tried redeploying a couple of times and still not picking up OpenNext v1.3.6 still using v1.3.5.

I've deleted my node modules, package-lock, and the .open-next folder and done a fresh npm install but still no joy.

Anything you suggest to make `npx sst deploy --stage prod` pick up the latest OpenNext version?

Cheers
Jack

**Comment by jacktomlinson** [comment]
@fwang was just having a dig-through on the commands being run... feel like this change a few days might mean this patch not getting picked up: https://github.com/serverless-stack/sst/commit/b87a96ffe2fb9d62754d025b0c950beec701d068

Feel like the change to using `@1.3.x` should work but I wonder if it is worth this instead? 

```
buildCommand: "npx --yes open-next@^1.3.0 build",
```

Fumbling around in the dark really any help be greatly appreciated, really want to use SST rather than Vercel but been a difficult first experience so far.

**Comment by fwang** [comment]
@jacktomlinson glad u got it working. Releases in the last 2 weeks had not been very stable, a lot of it was due to upstream bugs in Next.js making the switch from pages to app router.

v1.3.6 is now in a stable spot.

A few things we are going to put into OpenNext to ensure future stability:
1. Tests — adding tests for latest, and still-in-use past versions of Next.js (ie. 13.1.6, 12.3.4, etc)
2. Pinning OpenNext version — currently the `NextjsSite` always uses the latest patch pinning the minor version. (And the latest patch sometime aren't getting picked up by `npx` as u experienced). We will switch to making `open-next` a peer dependency of SST. And the end user will be in charge of pinning/updating the version. So no surprises.

^ oh btw.. if u haven't joined our [Discord channel](https://discord.gg/sst), definitely do. We are a lot more responsive in #open-next.
