### ISSUE TITLE
pnpm not supported

### ISSUE THREAD

**Issue by Farkal** [serverless-stack/sst#854]
The function `getTsBinPath`fail if we install packages with pnpm
```sh
 > matches
[
  '/Users/foo/Documents/Code/backend-test/node_modules/.pnpm/typescript@4.4.3/node_modules/typescript/lib/typescript.js',
  '/Users/foo/Documents/Code/backend-test/node_modules/.pnpm/typescript@4.4.3/node_modules',
  index: 0,
  input: '/Users/foo/Documents/Code/backend-test/node_modules/.pnpm/typescript@4.4.3/node_modules/typescript/lib/typescript.js',
  groups: undefined
]
> path.join(matches[1], ".bin", "tsc")
'/Users/foo/Documents/Code/backend-test/node_modules/.pnpm/typescript@4.4.3/node_modules/.bin/tsc'
```
It just miss the typescript folder before `.bin/tsc`but i think adding it would break installation with other package manager.

**Comment by deini** [comment]
Piggybacking from this issue, while we are at it, could we get support for `update` and `add-cdk` with pnpm too? 🙏

**Comment by thdxr** [comment]
Been meaning to try out pnpm. I'll take a look at this

**Comment by thdxr** [comment]
I started going down this path, I fixed the first few issues with tsc. But there's actually a lot of incompatibility deeper down with CDK itself. We're not too sure if we'll be able to support pnpm but we're going to be making a decision around it this week

**Comment by kierans** [comment]
> SST actually works fine with hoisting

I knew it would. However I couldn't get hoisting working with Rush using `pnpm`, which is why I switched to Rush using `npm`. It may not be pnpm's fault per se.

Using Rush with npm isn't that bad as all the node modules get installed to one place and symlinked everywhere so the benefits of using a monoreop are still there.

**Comment by mmkal** [comment]
@thdxr would be great to have a little more context on this - we have been successfully using CDK + pnpm + rush for the last year or so. We have a demo projects also deployed successfully with sst but we aren't using all of sst's features (e.g. add-cdk, we have typeCheck and lint disabled since we do those separately). Do you know _what_ exactly isn't supported? Or is it just that there are no guarantees?

**Comment by thdxr** [comment]
I need to do another deep dive into pnpm now that CDK v2 is out, some of what I say below may be outdated.

Next-gen bundlers like yarn2 + pnpm enforce certain constraints that some projects took advantage of.  For example, in CDK if they're including an asset that gets sent up with your cloudformation, they would resolve it using `__dirname`.  In yarn2 the filesystem for dependencies is "virtual" and you need to be using module resolution to find things. This leads to some things not working correctly.

If it works for you then I'd probably continue to use it until you hit something that isn't compatible.  I'll do another pass to see if I can test more thoroughly with cdkv2

**Comment by kierans** [comment]
> I need to do another deep dive into pnpm now that CDK v2 is out, some of what I say below may be outdated.

@thdxr It's probably because in CDK v2, all the AWS service constructs are [bundled together](https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html). Thus the issue of a non [flat folder structure ](https://github.com/serverless-stack/serverless-stack/issues/854#issuecomment-945016157) has gone away.

**Comment by Rawnly** [comment]
Any update on this? I'm currently using `pnpm-workspaces` and can't correctly run it ...

**Comment by Dzhuneyt** [comment]
I don't see how can that be a CDK issue where, in fact, I've worked on many monorepo projects that use AWS CDK + PNPM just fine, but attempting to configure a brand new basic monorepo with SST + PNPM leads to all sorts of errors like:

```
Preparing your SST app
node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@serverless-stack/core' imported from /Users/me/projects/acme-project/packages/backend/.build/run.mjs
Did you mean to import @serverless-stack+core@1.18.4/node_modules/@serverless-stack/core/dist/index.js?
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:930:9)
    at moduleResolve (node:internal/modules/esm/resolve:976:18)
    at defaultResolve (node:internal/modules/esm/resolve:1078:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}


There was an error synthesizing your app.
```

On the surface, it looks like SST is just relying too much on node_modules being a "local" folder, rather than being hoisted to the top of the monorepo. Because if we install the dependencies locally SST magically starts working.

**Comment by jayair** [comment]
We'll be releasing a public beta of the new CLI soon. With pnpm support.

**Comment by thdxr** [comment]
pnpm finally supported in v2!
